### ISSUE TITLE
Update snakeyaml to 2.0

### ISSUE THREAD

**Issue by ctrueden** [scijava/ui-behaviour#25]
The ome:formats-bsd component depends on snakeyaml 2.0, but this library still uses 1.x, creating a diamond dependency conflict for any library (such as sciview) that depends on both. Probably the easiest solution is to simply update this component to use 2.0, eh?

**Comment by vishalsingh2972** [comment]
@ctrueden can you assign this to me would like to work on it!

**Comment by ctrueden** [comment]
@vishalsingh2972 Great, thanks!

**Comment by ctrueden** [comment]
Fixed by #27.
