### ISSUE TITLE
double scroll events

### ISSUE THREAD

**Issue by funkey** [scijava/ui-behaviour#5]
In rare cases, the ScrollBehaviour gets into a state where it emits two scroll events for every mouse wheel event. Unfortunately, this is difficult to reproduce. If it happens, it happens right from the start of the application and stays like that.

Observed in [TranslateZController](https://github.com/saalfeldlab/bigcat/blob/janh5/src/main/java/bdv/bigcat/control/TranslateZController.java#L115).

**Comment by tpietzsch** [comment]
Hmm... Could you try to get it to happen in a debugger, and then see what happens in
https://github.com/scijava/ui-behaviour/blob/master/src/main/java/org/scijava/ui/behaviour/MouseAndKeyHandler.java#L317-L345
?

**Comment by funkey** [comment]
Sure, of course.

I found that all scroll `BehaviourEntry`s  appeared twice in the list `scrolls` when it happens. I suspect that in [`updateInternalMaps()`](https://github.com/scijava/ui-behaviour/blob/master/src/main/java/org/scijava/ui/behaviour/MouseAndKeyHandler.java#L121) a `scrolls.clear();` is missing.

However, I wonder why it happens only sometimes. `updateInternalMaps()` is only called from [`update()`](https://github.com/scijava/ui-behaviour/blob/master/src/main/java/org/scijava/ui/behaviour/MouseAndKeyHandler.java#L98), which is `synchronized`. So in some cases, between two calls to `update()`, the modification counts change. Not so surprising, since `update()` is triggered by AWT Events, and they come asynchronously and depend on what the user is doing with the mouse/keyboard during the initialization.

**Comment by tpietzsch** [comment]
Yes, awesome! That's it, good catch.

Your explanation is right, I think. It depends on whether `update()` is called already before the input/behaviourMaps have "settled". 

I'll fix it and release a new version.

**Comment by tpietzsch** [comment]
I released ui-behaviour 1,0.5.
Thanks again for finding this @funkey

**Comment by funkey** [comment]
You're welcome, and thanks for the quick fix!
